version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "3000:8080"
    volumes:
      - .:/go/src
    tty: true

  db:
    container_name: db
    image: mysql:8.0.15
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: gin_app
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: mysqld