version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "3000:8080"
    volumes:
      - .:/go/src
    tty: true
    depends_on:
      - "db"
    environment:
      TZ: Asia/Tokyo



  db:
    container_name: db
    image: mysql:8.0.15
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: gin_app
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: mysqld
    cap_add:
      - SYS_NICE

    # depends_on:
    #   - "app"